project:
  title: "Case-studies"
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - case-study-1-outline.qmd
    - case-study-1-challenges.qmd
    - case-study-1-suggestions.qmd
    - case-study-1-metadata.qmd
    - case-study-2.qmd
    - case-study-3.qmd
    - case-study-4.qmd
    - spoilers.qmd
website:
  google-analytics: "G-CCC4X0EP8B"
  title: "Case studies for Open Access sessions"
  repo-url: https://unisotonlibrary.github.io/Case-studies/
  repo-branch: main
  repo-actions:
    - edit
    - issue
  sidebar:
    style: docked
    contents:
      - href: index.qmd
        text: "Introduction"
      - href: case-study-1-outline.qmd
        text: "Case study 1: outline"
      - href: case-study-1-challenges.qmd
        text: "Case study 1: open access challenges"
      - href: case-study-1-suggestions.qmd
        text: "Case study 1: suggestions to overcome challenges"
      - href: case-study-1-metadata.qmd
        text: "Case study 1: metadata suggestions"
      - href: case-study-2.qmd
        text: "Case study 2"
      - href: case-study-3.qmd
        text: "Case study 3"
      - href: case-study-4.qmd
        text: "Case study 4"
      - href: spoilers.qmd
        text: "Spoilers!"
  page-footer: "Created by the University of Southampton Library with a CC0 licence"
format:
  html:
    link-external-newwindow: true
    link-external-icon: true
    theme:
      light: cosmo
      dark: darkly
    standalone: true
editor: visual